version: '3.8'

services:
  whisper-api:
    build: .
    container_name: whisper-transcription
    ports:
      - "8000:8000"
    volumes:
      - ./cache:/home/whisper/cache
      - ./logs:/home/whisper/logs
    environment:
      - LOG_LEVEL=INFO
      - MAX_FILE_SIZE_MB=100
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  nginx:
    image: nginx:alpine
    container_name: whisper-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - whisper-api
    restart: unless-stopped
