version: '3.8'

services:
  transcribe-optimized:
    build:
      context: .
      dockerfile: Dockerfile.optimized
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - OMP_NUM_THREADS=2
      - MKL_NUM_THREADS=2
    volumes:
      - ./cache:/app/cache
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 6G
        reservations:
          cpus: '1.0'
          memory: 2G
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

