FROM python:3.11-slim
WORKDIR /app
COPY requirements_pdf.txt .
RUN pip install -r requirements_pdf.txt
COPY src/transcribe_pdf.py .
CMD ["uvicorn","transcribe_pdf:app","--host","0.0.0.0","--port","8080"]